test:
  adapter: postgresql
  database: <%= ENV.fetch("TEST_DB_NAME") %>
  username: <%= ENV.fetch("TEST_DB_USER") %>
  password: <%= ENV.fetch("TEST_DB_PASSWORD") %>
  host: <%= ENV.fetch("TEST_DB_HOST") %>
  port: <%= ENV.fetch("TEST_DB_PORT") %>
