name: Publish @eshopguide/shopify-billing to npm

on:
  push:
    tags:
      - "v*" # Triggers on version tags like v1.2.3

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org/"

      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Set package.json version
        run: |
          yarn version --new-version "$VERSION" --no-git-tag-version

      - name: Install dependencies with Yarn
        run: yarn install --frozen-lockfile

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
