name: Ruby Tests and Linting

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: false

      - name: Update bundle platforms
        run: |
          bundle lock --add-platform x86_64-linux
          bundle install

      - name: Run RuboCop
        run: bundle exec rubocop

  test:
    needs: lint
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:14
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    env:
      RAILS_ENV: test
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      DB_NAME: lexoffice_test
      DB_USER: ${{ secrets.POSTGRES_DB_USER }}
      DB_PASSWORD: ${{ secrets.POSTGRES_DB_PASSWORD }}
      HOST_NAME: localhost
      APP_HOME: https://test-host/
      APP_NAME: lexoffice-integration
      CENTRAL_EVENT_LOGGER_API_BASE_URL: https://testurl.com
      CENTRAL_EVENT_LOGGER_API_KEY: test_key
      CENTRAL_EVENT_LOGGER_API_SECRET: test_secret
      REPORTING_JOB_QUEUE: default
      TRIAL_DAYS: 7
      TEST_CHARGE: true

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: false

      - name: Update bundle platforms
        run: |
          bundle lock --add-platform x86_64-linux
          bundle install

      - name: Setup database
        run: |
          bundle exec rails db:create db:schema:load

      - name: Run tests
        run: bundle exec rspec

      - name: Upload coverage results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: coverage