name: RSpec

on: [push, workflow_dispatch]

jobs:
  check_commit:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.skip_check.outputs.skip }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check for skip ci tag in commit message
        id: skip_check
        run: |
          echo "::set-output name=skip::$(git log -1 --pretty=%B | grep -E '\[skip ci\]|\[ci skip\]|\[no ci\]' && echo 'true' || echo 'false')"

  rspec:
    needs: check_commit
    if: needs.check_commit.outputs.skip == 'false'
    runs-on: ubuntu-latest
    name: Run RSpec tests

    services:
      postgres:
        image: postgres:13.2
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.4
          bundler-cache: false

      - uses: actions/setup-node@v3
        with:
          node-version: 16.19.0

      - name: Cache Bundler
        uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: bundler-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            bundler-

      - name: Install dependent libraries
        run: sudo apt-get install libpq-dev

      - name: Update bundle platforms
        run: |
          bundle lock --add-platform x86_64-linux
          bundle install

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --path vendor/bundle

      - name: Set up environment variables
        run: |
          echo "DB_NAME=lexoffice_test" >> $GITHUB_ENV
          echo "DB_USER=postgres" >> $GITHUB_ENV
          echo "DB_PASSWORD=postgres" >> $GITHUB_ENV
          echo "DB_HOST=localhost" >> $GITHUB_ENV
          echo "DB_PORT=5432" >> $GITHUB_ENV
          echo "APP_NAME=ShopifyBilling" >> $GITHUB_ENV
          echo "TRIAL_DAYS=14" >> $GITHUB_ENV
          echo "HOST_NAME=localhost" >> $GITHUB_ENV
          echo "TEST_CHARGE=true" >> $GITHUB_ENV

      - name: Create database.yml for Combustion
        run: |
          mkdir -p spec/internal/config
          cat > spec/internal/config/database.yml << EOF
          test:
            adapter: postgresql
            database: lexoffice_test
            username: postgres
            password: postgres
            host: localhost
            port: 5432
          EOF

      - name: Set up test database
        run: |
          bundle exec ruby -e "require 'combustion'; Combustion.initialize! :active_record; ActiveRecord::Tasks::DatabaseTasks.create_current; ActiveRecord::Tasks::DatabaseTasks.load_schema_current"
        env:
          RAILS_ENV: test

      - name: Assets Cache
        id: assets-cache
        uses: actions/cache@v4
        with:
          path: public/packs-test
          key: ${{ runner.os }}-assets-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-assets-

      - name: Run RSpec tests
        run: |
          bundle exec rspec
        env:
          RAILS_ENV: test
          DB_NAME: lexoffice_test
          DB_USER: postgres
          DB_PASSWORD: postgres
          DB_HOST: localhost
          DB_PORT: 5432
          HOST_NAME: localhost
          APP_NAME: ShopifyBilling
          TRIAL_DAYS: 14
          TEST_CHARGE: true