name: Ruby Tests and Linting

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: false

      - name: Update bundle platforms
        run: |
          bundle lock --add-platform x86_64-linux
          bundle install

      - name: Run RuboCop
        run: bundle exec rubocop

  test:
    needs: lint
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: shopify_billing_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/shopify_billing_test
      TRIAL_DAYS: 14
      APP_NAME: ShopifyBilling
      HOST_NAME: example.com
      TEST_CHARGE: true

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: false

      - name: Update bundle platforms
        run: |
          bundle lock --add-platform x86_64-linux
          bundle install

      - name: Setup database
        run: |
          bundle exec rake test:setup

      - name: Run tests
        run: bundle exec rspec

      - name: Upload coverage results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: coverage